from pathlib import Path
import base64, gzip, subprocess, sys

if len(sys.argv) != 2:
    raise SystemExit('usage: generic_forced_induction_v1_patch.py <engine-sim-source>')
root=Path(sys.argv[1]).resolve()
if not (root/'CMakeLists.txt').exists():
    raise SystemExit('generic forced-induction patch: source root missing CMakeLists.txt')

parts = sorted(Path(__file__).resolve().parent.glob('generic_v1.part*.b64'))
if not parts:
    raise SystemExit('generic forced-induction core patch payload parts missing')
patch_bytes = gzip.decompress(base64.b64decode(''.join(x.read_text(encoding='ascii').strip() for x in parts)))
AFFECTED = ['include/intake.h','src/intake.cpp','include/exhaust_system.h','src/exhaust_system.cpp','include/engine.h','src/engine.cpp','include/combustion_chamber.h','src/combustion_chamber.cpp','src/piston_engine_simulator.cpp','test/diesel_turbo_model_tests.cpp','test/runtime_engine_smoke.cpp']
for rel in AFFECTED:
    q=root/rel
    q.write_text(q.read_text(encoding='utf-8'),encoding='utf-8',newline='\n')
patch_path=root/'.generic_forced_induction_v1.patch'
patch_path.write_bytes(patch_bytes)
try:
    check=subprocess.run(['git','-C',str(root),'apply','--check','--whitespace=nowarn',str(patch_path)])
    if check.returncode != 0: raise SystemExit('generic forced-induction core patch preflight failed')
    apply=subprocess.run(['git','-C',str(root),'apply','--whitespace=nowarn',str(patch_path)])
    if apply.returncode != 0: raise SystemExit('generic forced-induction core patch failed')
finally:
    if patch_path.exists(): patch_path.unlink()

def rep(path, old, new):
    p=root/path
    s=p.read_text(encoding='utf-8')
    if old not in s: raise SystemExit(f'generic forced-induction patch anchor missing in {path}: {old[:120]!r}')
    p.write_text(s.replace(old,new,1),encoding='utf-8',newline='\n')

rep('CMakeLists.txt', '    src/turbocharger_model.cpp\n    src/procedural_diesel_audio.cpp', '    src/turbocharger_model.cpp\n    src/turbo_group.cpp\n    src/procedural_diesel_audio.cpp')
rep('scripting/include/engine_node.h', '            addInput("turbo_design_mass_flow", &m_parameters.turbocharger.designMassFlow);\n', '            addInput("turbo_design_mass_flow", &m_parameters.turbocharger.designMassFlow);\n            addInput("turbo_design_pressure_ratio", &m_parameters.turbocharger.turbineDesignPressureRatio);\n            addInput("turbo_design_temperature", &m_parameters.turbocharger.turbineDesignTemperature);\n            addInput("turbo_pre_turbine_volume", &m_parameters.turboGroup.preTurbineVolume);\n            addInput("turbo_pre_turbine_area", &m_parameters.turboGroup.preTurbineCrossSectionArea);\n            addInput("turbo_inlet_channel_count", &m_parameters.turboGroup.turbineInletChannels);\n            addInput("turbo_compressor_inlet_volume", &m_parameters.turboGroup.compressorInletVolume);\n            addInput("turbo_compressor_discharge_volume", &m_parameters.turboGroup.compressorDischargeVolume);\n            addInput("turbo_charge_plenum_volume", &m_parameters.turboGroup.chargePlenumVolume);\n            addInput("turbo_charge_area", &m_parameters.turboGroup.chargeCrossSectionArea);\n            addInput("turbo_inlet_flow_rate", &m_parameters.turboGroup.compressorInletFlowK);\n            addInput("turbo_passive_compressor_flow_rate", &m_parameters.turboGroup.passiveCompressorFlowK);\n            addInput("turbo_cooler_flow_rate", &m_parameters.turboGroup.coolerFlowK);\n            addInput("wastegate_enabled", &m_parameters.turboGroup.wastegateEnabled);\n            addInput("wastegate_flow_rate", &m_parameters.turboGroup.wastegateFlowK);\n            addInput("wastegate_position", &m_parameters.turboGroup.wastegatePosition);\n            addInput("compressor_bypass_enabled", &m_parameters.turboGroup.compressorBypassEnabled);\n            addInput("compressor_bypass_flow_rate", &m_parameters.turboGroup.compressorBypassFlowK);\n            addInput("compressor_bypass_position", &m_parameters.turboGroup.compressorBypassPosition);\n            addInput("compressor_bypass_recirculates", &m_parameters.turboGroup.compressorBypassRecirculates);\n            addInput("vgt_enabled", &m_parameters.turboGroup.variableGeometryEnabled);\n            addInput("vgt_position", &m_parameters.turboGroup.variableGeometryPosition);\n            addInput("vgt_min_flow_factor", &m_parameters.turboGroup.variableGeometryMinFlowFactor);\n')
rep('es/objects/objects.mr', '    input turbo_design_mass_flow [float];\n    input audio_low_speed_full_strength [float];', '    input turbo_design_mass_flow [float];\n    input turbo_design_pressure_ratio [float];\n    input turbo_design_temperature [float];\n    input turbo_pre_turbine_volume [float];\n    input turbo_pre_turbine_area [float];\n    input turbo_inlet_channel_count [int];\n    input turbo_compressor_inlet_volume [float];\n    input turbo_compressor_discharge_volume [float];\n    input turbo_charge_plenum_volume [float];\n    input turbo_charge_area [float];\n    input turbo_inlet_flow_rate [float];\n    input turbo_passive_compressor_flow_rate [float];\n    input turbo_cooler_flow_rate [float];\n    input wastegate_enabled [bool];\n    input wastegate_flow_rate [float];\n    input wastegate_position [float];\n    input compressor_bypass_enabled [bool];\n    input compressor_bypass_flow_rate [float];\n    input compressor_bypass_position [float];\n    input compressor_bypass_recirculates [bool];\n    input vgt_enabled [bool];\n    input vgt_position [float];\n    input vgt_min_flow_factor [float];\n    input audio_low_speed_full_strength [float];')
rep('es/objects/objects.mr', '    input turbo_design_mass_flow: 1.0 * units.kg / units.sec;\n    input audio_low_speed_full_strength: 40 * units.rpm;', '    input turbo_design_mass_flow: 1.0 * units.kg / units.sec;\n    input turbo_design_pressure_ratio: 1.8;\n    input turbo_design_temperature: 800 * units.K;\n    input turbo_pre_turbine_volume: 1.0 * units.L;\n    input turbo_pre_turbine_area: 10.0 * units.cm2;\n    input turbo_inlet_channel_count: 1;\n    input turbo_compressor_inlet_volume: 1.0 * units.L;\n    input turbo_compressor_discharge_volume: 1.0 * units.L;\n    input turbo_charge_plenum_volume: 1.0 * units.L;\n    input turbo_charge_area: 10.0 * units.cm2;\n    input turbo_inlet_flow_rate: 0.0;\n    input turbo_passive_compressor_flow_rate: 0.0;\n    input turbo_cooler_flow_rate: 0.0;\n    input wastegate_enabled: false;\n    input wastegate_flow_rate: 0.0;\n    input wastegate_position: 0.0;\n    input compressor_bypass_enabled: false;\n    input compressor_bypass_flow_rate: 0.0;\n    input compressor_bypass_position: 0.0;\n    input compressor_bypass_recirculates: true;\n    input vgt_enabled: false;\n    input vgt_position: 1.0;\n    input vgt_min_flow_factor: 0.25;\n    input audio_low_speed_full_strength: 40 * units.rpm;')
rep('es/objects/objects.mr', '            turbo_design_mass_flow: turbo_design_mass_flow,\n            audio_low_speed_full_strength: audio_low_speed_full_strength,', '            turbo_design_mass_flow: turbo_design_mass_flow,\n            turbo_design_pressure_ratio: turbo_design_pressure_ratio,\n            turbo_design_temperature: turbo_design_temperature,\n            turbo_pre_turbine_volume: turbo_pre_turbine_volume,\n            turbo_pre_turbine_area: turbo_pre_turbine_area,\n            turbo_inlet_channel_count: turbo_inlet_channel_count,\n            turbo_compressor_inlet_volume: turbo_compressor_inlet_volume,\n            turbo_compressor_discharge_volume: turbo_compressor_discharge_volume,\n            turbo_charge_plenum_volume: turbo_charge_plenum_volume,\n            turbo_charge_area: turbo_charge_area,\n            turbo_inlet_flow_rate: turbo_inlet_flow_rate,\n            turbo_passive_compressor_flow_rate: turbo_passive_compressor_flow_rate,\n            turbo_cooler_flow_rate: turbo_cooler_flow_rate,\n            wastegate_enabled: wastegate_enabled,\n            wastegate_flow_rate: wastegate_flow_rate,\n            wastegate_position: wastegate_position,\n            compressor_bypass_enabled: compressor_bypass_enabled,\n            compressor_bypass_flow_rate: compressor_bypass_flow_rate,\n            compressor_bypass_position: compressor_bypass_position,\n            compressor_bypass_recirculates: compressor_bypass_recirculates,\n            vgt_enabled: vgt_enabled,\n            vgt_position: vgt_position,\n            vgt_min_flow_factor: vgt_min_flow_factor,\n            audio_low_speed_full_strength: audio_low_speed_full_strength,')
print('generic forced-induction V1 architecture applied')
